"""initial commerce core

Revision ID: 6c88e7c6b354
Revises:
Create Date: 2026-08-29 10:53:29.217022
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "6c88e7c6b354"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "INACTIVE", name="merchantstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("settings", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_slug"), "merchants", ["slug"], unique=True)
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("event_id", sa.String(length=160), nullable=False),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("processed", sa.Boolean(), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "event_id", name="uq_webhook_provider_event"),
    )
    op.create_index(
        op.f("ix_webhook_events_event_type"), "webhook_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_processed"), "webhook_events", ["processed"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_events_received_at"), "webhook_events", ["received_at"], unique=False
    )
    op.create_table(
        "audit_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("actor_type", sa.String(length=40), nullable=False),
        sa.Column("actor_id", sa.String(length=160), nullable=True),
        sa.Column("event_type", sa.String(length=120), nullable=False),
        sa.Column("aggregate_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.String(length=120), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_aggregate", "audit_events", ["aggregate_type", "aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_aggregate_id"), "audit_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_aggregate_type"), "audit_events", ["aggregate_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_merchant_id"), "audit_events", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_occurred_at"), "audit_events", ["occurred_at"], unique=False
    )
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("CAFE", "ROASTERY", "FULFILLMENT_HUB", name="locationkind", native_enum=False),
            nullable=False,
        ),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("longitude", sa.Numeric(precision=9, scale=6), nullable=True),
        sa.Column("address", sa.JSON(), nullable=False),
        sa.Column("postal_code", sa.String(length=20), nullable=False),
        sa.Column("preparation_minutes", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "slug", name="uq_location_merchant_slug"),
    )
    op.create_index(op.f("ix_locations_active"), "locations", ["active"], unique=False)
    op.create_index(op.f("ix_locations_merchant_id"), "locations", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_locations_postal_code"), "locations", ["postal_code"], unique=False)
    op.create_table(
        "products",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("name", sa.String(length=180), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "product_type",
            sa.Enum(
                "PREPARED_BEVERAGE",
                "PACKAGED_COFFEE",
                "PACKAGED_TEA",
                "ACCESSORY",
                name="producttype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("DRAFT", "ACTIVE", "ARCHIVED", name="productstatus", native_enum=False),
            nullable=False,
        ),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("image_urls", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "slug", name="uq_product_merchant_slug"),
    )
    op.create_index(op.f("ix_products_merchant_id"), "products", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_products_name"), "products", ["name"], unique=False)
    op.create_index(op.f("ix_products_status"), "products", ["status"], unique=False)
    op.create_table(
        "scheduled_purchase_intents",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("customer_reference", sa.String(length=120), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "PAUSED",
                "COMPLETED",
                "EXPIRED",
                name="purchaseintentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("constraints", sa.JSON(), nullable=False),
        sa.Column("authorization_reference", sa.String(length=200), nullable=True),
        sa.Column("payment_token_reference", sa.String(length=200), nullable=True),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scheduled_purchase_intents_customer_reference"),
        "scheduled_purchase_intents",
        ["customer_reference"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_purchase_intents_merchant_id"),
        "scheduled_purchase_intents",
        ["merchant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_scheduled_purchase_intents_next_run_at"),
        "scheduled_purchase_intents",
        ["next_run_at"],
        unique=False,
    )
    op.create_table(
        "checkouts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "READY_FOR_APPROVAL",
                "APPROVED",
                "PAYMENT_PENDING",
                "COMPLETED",
                "CANCELED",
                "EXPIRED",
                name="checkoutstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("idempotency_key", sa.String(length=128), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "fulfillment_type",
            sa.Enum(
                "PICKUP", "LOCAL_DELIVERY", "SHIPPING", name="fulfillmenttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("delivery_address", sa.JSON(), nullable=True),
        sa.Column("subtotal_minor", sa.Integer(), nullable=False),
        sa.Column("delivery_minor", sa.Integer(), nullable=False),
        sa.Column("discount_minor", sa.Integer(), nullable=False),
        sa.Column("tax_minor", sa.Integer(), nullable=False),
        sa.Column("tax_included", sa.Boolean(), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("quote_version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("delivery_minor >= 0", name="ck_checkout_delivery_nonnegative"),
        sa.CheckConstraint("discount_minor >= 0", name="ck_checkout_discount_nonnegative"),
        sa.CheckConstraint("subtotal_minor >= 0", name="ck_checkout_subtotal_nonnegative"),
        sa.CheckConstraint("total_minor >= 0", name="ck_checkout_total_nonnegative"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "idempotency_key", name="uq_checkout_idempotency"),
    )
    op.create_index(op.f("ix_checkouts_expires_at"), "checkouts", ["expires_at"], unique=False)
    op.create_index(op.f("ix_checkouts_location_id"), "checkouts", ["location_id"], unique=False)
    op.create_index(op.f("ix_checkouts_merchant_id"), "checkouts", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_checkouts_status"), "checkouts", ["status"], unique=False)
    op.create_table(
        "location_hours",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("opens_at", sa.Time(), nullable=True),
        sa.Column("closes_at", sa.Time(), nullable=True),
        sa.Column("closed", sa.Boolean(), nullable=False),
        sa.CheckConstraint("weekday >= 0 AND weekday <= 6", name="ck_location_hours_weekday"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "weekday", name="uq_location_hours_weekday"),
    )
    op.create_index(
        op.f("ix_location_hours_location_id"), "location_hours", ["location_id"], unique=False
    )
    op.create_table(
        "modifier_groups",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("minimum_selections", sa.Integer(), nullable=False),
        sa.Column("maximum_selections", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modifier_groups_product_id"), "modifier_groups", ["product_id"], unique=False
    )
    op.create_table(
        "product_variants",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("price_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("size_label", sa.String(length=80), nullable=True),
        sa.Column("weight_grams", sa.Integer(), nullable=True),
        sa.Column("preparation_minutes", sa.Integer(), nullable=False),
        sa.Column("track_inventory", sa.Boolean(), nullable=False),
        sa.Column("sellable", sa.Boolean(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price_minor >= 0", name="ck_variant_price_nonnegative"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "sku", name="uq_variant_merchant_sku"),
    )
    op.create_index(
        op.f("ix_product_variants_merchant_id"), "product_variants", ["merchant_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_product_id"), "product_variants", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_variants_sellable"), "product_variants", ["sellable"], unique=False
    )
    op.create_table(
        "service_zones",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "fulfillment_type",
            sa.Enum(
                "PICKUP", "LOCAL_DELIVERY", "SHIPPING", name="fulfillmenttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("postal_codes", sa.JSON(), nullable=False),
        sa.Column("radius_km", sa.Numeric(precision=6, scale=2), nullable=True),
        sa.Column("minimum_order_minor", sa.Integer(), nullable=False),
        sa.Column("fee_minor", sa.Integer(), nullable=False),
        sa.Column("free_above_minor", sa.Integer(), nullable=True),
        sa.Column("eta_min_minutes", sa.Integer(), nullable=False),
        sa.Column("eta_max_minutes", sa.Integer(), nullable=False),
        sa.Column("cutoff_time", sa.Time(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_service_zones_location_id"), "service_zones", ["location_id"], unique=False
    )
    op.create_table(
        "checkout_fulfillment_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.Column("service_zone_id", sa.Uuid(), nullable=True),
        sa.Column(
            "fulfillment_type",
            sa.Enum(
                "PICKUP", "LOCAL_DELIVERY", "SHIPPING", name="fulfillmenttype", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("fee_minor", sa.Integer(), nullable=False),
        sa.Column("eta_min_minutes", sa.Integer(), nullable=False),
        sa.Column("eta_max_minutes", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkouts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["service_zone_id"], ["service_zones.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkout_fulfillment_options_checkout_id"),
        "checkout_fulfillment_options",
        ["checkout_id"],
        unique=False,
    )
    op.create_table(
        "checkout_line_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_minor", sa.Integer(), nullable=False),
        sa.Column("modifier_total_minor", sa.Integer(), nullable=False),
        sa.Column("line_total_minor", sa.Integer(), nullable=False),
        sa.Column("product_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("line_total_minor >= 0", name="ck_checkout_line_total_nonnegative"),
        sa.CheckConstraint(
            "modifier_total_minor >= 0", name="ck_checkout_line_modifier_nonnegative"
        ),
        sa.CheckConstraint("quantity > 0", name="ck_checkout_line_quantity_positive"),
        sa.CheckConstraint("unit_price_minor >= 0", name="ck_checkout_line_unit_price_nonnegative"),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkouts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkout_line_items_checkout_id"),
        "checkout_line_items",
        ["checkout_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_checkout_line_items_variant_id"),
        "checkout_line_items",
        ["variant_id"],
        unique=False,
    )
    op.create_table(
        "inventory_batches",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("lot_code", sa.String(length=80), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("roasted_at", sa.Date(), nullable=True),
        sa.Column("best_before", sa.Date(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "lot_code", name="uq_inventory_batch_location_lot"),
    )
    op.create_index(
        op.f("ix_inventory_batches_location_id"), "inventory_batches", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_batches_variant_id"), "inventory_batches", ["variant_id"], unique=False
    )
    op.create_table(
        "inventory_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("variant_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand_quantity", sa.Integer(), nullable=False),
        sa.Column("reserved_quantity", sa.Integer(), nullable=False),
        sa.Column("reorder_point", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("on_hand_quantity >= 0", name="ck_inventory_on_hand_nonnegative"),
        sa.CheckConstraint(
            "reserved_quantity <= on_hand_quantity", name="ck_inventory_reserved_within_on_hand"
        ),
        sa.CheckConstraint("reserved_quantity >= 0", name="ck_inventory_reserved_nonnegative"),
        sa.ForeignKeyConstraint(["location_id"], ["locations.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["variant_id"], ["product_variants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("location_id", "variant_id", name="uq_inventory_location_variant"),
    )
    op.create_index(
        op.f("ix_inventory_items_location_id"), "inventory_items", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_items_variant_id"), "inventory_items", ["variant_id"], unique=False
    )
    op.create_index(
        "ix_inventory_variant_location",
        "inventory_items",
        ["variant_id", "location_id"],
        unique=False,
    )
    op.create_table(
        "modifier_options",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("group_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_delta_minor", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("price_delta_minor >= 0", name="ck_modifier_price_nonnegative"),
        sa.ForeignKeyConstraint(["group_id"], ["modifier_groups.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_modifier_options_group_id"), "modifier_options", ["group_id"], unique=False
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("merchant_id", sa.Uuid(), nullable=False),
        sa.Column("checkout_id", sa.Uuid(), nullable=False),
        sa.Column("public_number", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "AWAITING_PAYMENT",
                "PAID",
                "PREPARING",
                "READY",
                "FULFILLED",
                "CANCELED",
                name="orderstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("total_minor", sa.Integer(), nullable=False),
        sa.Column("fulfillment_snapshot", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["checkout_id"], ["checkouts.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["merchant_id"], ["merchants.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("checkout_id"),
    )
    op.create_index(op.f("ix_orders_merchant_id"), "orders", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_orders_public_number"), "orders", ["public_number"], unique=True)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_table(
        "checkout_line_modifiers",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("line_item_id", sa.Uuid(), nullable=False),
        sa.Column("modifier_option_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("price_delta_minor", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["line_item_id"], ["checkout_line_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["modifier_option_id"], ["modifier_options.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_checkout_line_modifiers_line_item_id"),
        "checkout_line_modifiers",
        ["line_item_id"],
        unique=False,
    )
    op.create_table(
        "inventory_reservations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("checkout_line_item_id", sa.Uuid(), nullable=False),
        sa.Column("inventory_item_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "ACTIVE",
                "RELEASED",
                "CONSUMED",
                "EXPIRED",
                name="reservationstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["checkout_line_item_id"], ["checkout_line_items.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["inventory_item_id"], ["inventory_items.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inventory_reservations_checkout_line_item_id"),
        "inventory_reservations",
        ["checkout_line_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_expires_at"),
        "inventory_reservations",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_inventory_item_id"),
        "inventory_reservations",
        ["inventory_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_reservations_status"), "inventory_reservations", ["status"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("provider_order_id", sa.String(length=120), nullable=True),
        sa.Column("provider_payment_id", sa.String(length=120), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "AUTHORIZED",
                "CAPTURED",
                "FAILED",
                "REFUNDED",
                name="paymentstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount_minor", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("failure_code", sa.String(length=120), nullable=True),
        sa.Column("failure_description", sa.Text(), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["order_id"], ["orders.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_payment_id", name="uq_provider_payment"),
    )
    op.create_index(op.f("ix_payments_order_id"), "payments", ["order_id"], unique=False)
    op.create_index(
        op.f("ix_payments_provider_order_id"), "payments", ["provider_order_id"], unique=False
    )
    op.create_index(op.f("ix_payments_status"), "payments", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_status"), table_name="payments")
    op.drop_index(op.f("ix_payments_provider_order_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_order_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_inventory_reservations_status"), table_name="inventory_reservations")
    op.drop_index(
        op.f("ix_inventory_reservations_inventory_item_id"), table_name="inventory_reservations"
    )
    op.drop_index(op.f("ix_inventory_reservations_expires_at"), table_name="inventory_reservations")
    op.drop_index(
        op.f("ix_inventory_reservations_checkout_line_item_id"), table_name="inventory_reservations"
    )
    op.drop_table("inventory_reservations")
    op.drop_index(
        op.f("ix_checkout_line_modifiers_line_item_id"), table_name="checkout_line_modifiers"
    )
    op.drop_table("checkout_line_modifiers")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_public_number"), table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_modifier_options_group_id"), table_name="modifier_options")
    op.drop_table("modifier_options")
    op.drop_index("ix_inventory_variant_location", table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_variant_id"), table_name="inventory_items")
    op.drop_index(op.f("ix_inventory_items_location_id"), table_name="inventory_items")
    op.drop_table("inventory_items")
    op.drop_index(op.f("ix_inventory_batches_variant_id"), table_name="inventory_batches")
    op.drop_index(op.f("ix_inventory_batches_location_id"), table_name="inventory_batches")
    op.drop_table("inventory_batches")
    op.drop_index(op.f("ix_checkout_line_items_variant_id"), table_name="checkout_line_items")
    op.drop_index(op.f("ix_checkout_line_items_checkout_id"), table_name="checkout_line_items")
    op.drop_table("checkout_line_items")
    op.drop_index(
        op.f("ix_checkout_fulfillment_options_checkout_id"),
        table_name="checkout_fulfillment_options",
    )
    op.drop_table("checkout_fulfillment_options")
    op.drop_index(op.f("ix_service_zones_location_id"), table_name="service_zones")
    op.drop_table("service_zones")
    op.drop_index(op.f("ix_product_variants_sellable"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_product_id"), table_name="product_variants")
    op.drop_index(op.f("ix_product_variants_merchant_id"), table_name="product_variants")
    op.drop_table("product_variants")
    op.drop_index(op.f("ix_modifier_groups_product_id"), table_name="modifier_groups")
    op.drop_table("modifier_groups")
    op.drop_index(op.f("ix_location_hours_location_id"), table_name="location_hours")
    op.drop_table("location_hours")
    op.drop_index(op.f("ix_checkouts_status"), table_name="checkouts")
    op.drop_index(op.f("ix_checkouts_merchant_id"), table_name="checkouts")
    op.drop_index(op.f("ix_checkouts_location_id"), table_name="checkouts")
    op.drop_index(op.f("ix_checkouts_expires_at"), table_name="checkouts")
    op.drop_table("checkouts")
    op.drop_index(
        op.f("ix_scheduled_purchase_intents_next_run_at"), table_name="scheduled_purchase_intents"
    )
    op.drop_index(
        op.f("ix_scheduled_purchase_intents_merchant_id"), table_name="scheduled_purchase_intents"
    )
    op.drop_index(
        op.f("ix_scheduled_purchase_intents_customer_reference"),
        table_name="scheduled_purchase_intents",
    )
    op.drop_table("scheduled_purchase_intents")
    op.drop_index(op.f("ix_products_status"), table_name="products")
    op.drop_index(op.f("ix_products_name"), table_name="products")
    op.drop_index(op.f("ix_products_merchant_id"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_locations_postal_code"), table_name="locations")
    op.drop_index(op.f("ix_locations_merchant_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_active"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_audit_events_occurred_at"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_merchant_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_aggregate_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_aggregate_id"), table_name="audit_events")
    op.drop_index("ix_audit_aggregate", table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_webhook_events_received_at"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_processed"), table_name="webhook_events")
    op.drop_index(op.f("ix_webhook_events_event_type"), table_name="webhook_events")
    op.drop_table("webhook_events")
    op.drop_index(op.f("ix_merchants_slug"), table_name="merchants")
    op.drop_table("merchants")
    # ### end Alembic commands ###
